//! `TwinNetPSK(A, B, epoch)` — the `psk2` slot, and the one TwinVPN-designed
//! derivation.
//!
//! **Authority:** ADR-0007 §7.7 **lines 654-657**, which is the operative text;
//! ADR-0007 §10 (the overrule); ADR-0001 §7.5 and §11 item 7;
//! `docs/architecture.md` S-33.
//!
//! # Read ADR-0007 §7.7, not ADR-0001 §7.5
//!
//! ADR-0001 §7.5 writes this derivation with an ellipsis —
//! `HKDF-SHA-256( ikm = …, ... )` — and it is **superseded**. ADR-0001 §7.5
//! itself points at the correction ("ADR-0007 §7.7, which **corrects** an
//! earlier form of this paragraph"), and ADR-0007 §10 states the overrule in
//! terms:
//!
//! > "**ADR-0001 §7.5 item 2 — Overruled.** A TwinNet-wide PSK secret makes the
//! > epoch worthless as a revocation lever. Replaced by pairwise `PairSecret` +
//! > per-device-sealed `EpochSeed` (§7.7). ADR-0001 §7.5 must be amended."
//!
//! **The corpus fully specifies every parameter.** ADR-0007 §7.7, verbatim:
//!
//! ```text
//! EpochSeed(e)      : 32 random bytes, generated by the revoking OSK device
//! TwinNetPSK(A,B,e) = HKDF-SHA-256( ikm  = PairSecret(A,B) || EpochSeed(e),
//!                                   salt = twinnet_id || e (u64 BE),
//!                                   info = "TwinVPN/psk2/v1" )
//! ```
//!
//! That is what [`TwinNetPsk::derive`] computes, byte for byte, and
//! `the_derivation_matches_adr_0007_7_7_line_654` pins it against a vector
//! computed from the ADR's text rather than from this code.
//!
//! # Why the peer identities are not inputs
//!
//! They do not appear in the formula, and they must not be added. The pairwise
//! binding is already carried by `PairSecret(A,B)`, which ADR-0007 N-19 makes
//! per-pair by construction and which "MUST NOT be transmitted, backed up, or
//! replicated". Folding the `device_id`s in as well would be redundant, would
//! raise the question of their ordering, and — decisively — would make this
//! implementation's `psk2` disagree with a conforming one.
//!
//! # What each half of the `ikm` is for
//!
//! ADR-0007 §7.7 states the property the split exists to provide:
//!
//! > "A revoked device is simply not a recipient, so it cannot compute the PSK
//! > at epoch `e` **even if it retained its `PairSecret` and even if a peer's
//! > `TrustedPeer` deletion failed**."
//!
//! and why a `TwinNet`-wide secret would not do:
//!
//! > "derived from a *TwinNet-wide* secret, the PSK epoch would **not** be a
//! > revocation lever, because the revoked device would know that secret and
//! > could derive any later epoch's PSK. Derived from a *pairwise* secret plus
//! > an OSK-generated, per-device-sealed epoch seed, it is."
//!
//! So [`TwinNetPsk::derive`] takes **both** halves and there is no constructor
//! taking one: a `TwinNetPsk` derivable from a single secret would be a PSK
//! whose epoch is not a revocation lever, which is ADR-0001 R13 silently lost.

use crate::kdf::hkdf_sha256;
use crate::locked::LockedBytes;
use crate::{CryptoError, Result};

/// The `psk2` slot's width, fixed by Noise (`PSKLEN`).
pub const PSK_LEN: usize = 32;

/// `EpochSeed(e)`'s width.
///
/// ADR-0007 §7.7 line 654: "`EpochSeed(e)` : **32 random bytes**, generated by
/// the revoking OSK device". Enforced rather than assumed, because a short seed
/// would still derive *a* PSK — one with less entropy than the revocation lever
/// depends on, and nothing downstream would notice.
pub const EPOCH_SEED_LEN: usize = 32;

/// The HKDF `info`, verbatim from ADR-0007 §7.7 line 657.
///
/// ```text
/// info = "TwinVPN/psk2/v1"
/// ```
///
/// Exactly this ASCII literal: no epoch, no device ids, no length prefix. The
/// distinguishing inputs live in the `salt` and the `ikm`, which is where the
/// ADR puts them.
pub const PSK_INFO: &[u8] = b"TwinVPN/psk2/v1";

/// Builds the HKDF `salt`, verbatim from ADR-0007 §7.7 line 656.
///
/// ```text
/// salt = twinnet_id || e (u64 BE)
/// ```
///
/// The `twinnet_id` goes in as its **raw UTF-8 bytes**. It is a
/// `tstr .size (1..64)` in `contracts/cddl/twinvpn/v1/signed_statements.cddl`,
/// and HKDF's salt is variable-length by construction (RFC 5869 §2.2), so no
/// contraction is needed or permitted here — see [`crate::prologue::TwinnetTag`],
/// which is the *other*, fixed-width use and does need one.
///
/// The concatenation is unambiguous as the ADR writes it because the epoch is
/// fixed-width and **last**: the trailing eight bytes can always be peeled off.
/// A length prefix would be an improvement on a specified format, which is not
/// ours to make.
#[must_use]
pub fn psk_salt(twinnet_id: &str, epoch: u64) -> Vec<u8> {
    let id = twinnet_id.as_bytes();
    let mut salt = Vec::with_capacity(id.len() + 8);
    salt.extend_from_slice(id);
    salt.extend_from_slice(&epoch.to_be_bytes());
    salt
}

/// A `TwinNetPSK` for one peer pair at one epoch.
///
/// Held in [`LockedBytes`]: it is a symmetric secret that, combined with an
/// extracted static, completes a handshake. It is not one of CB-5's two
/// core-held *key* rows — it is derived material with the same lifetime as the
/// session state around it — but it gets the same custody, because there is no
/// reason for it to be weaker than the `TK` it sits beside.
pub struct TwinNetPsk {
    bytes: LockedBytes,
    epoch: u64,
}

impl TwinNetPsk {
    /// Derives `TwinNetPSK(A, B, epoch)` exactly as ADR-0007 §7.7 line 655
    /// writes it.
    ///
    /// `pair_secret` is the pairwise `PairSecret` established by the pairing
    /// ceremony (N-19). `epoch_seed` is the plaintext `EpochSeed(epoch)`, which
    /// reaches this device only as an HPKE seal addressed to it (S-33) and
    /// which this crate therefore receives already opened by the caller.
    /// `twinnet_id` and `epoch` form the salt.
    ///
    /// # Errors
    ///
    /// [`CryptoError::KeyLength`] if `epoch_seed` is not [`EPOCH_SEED_LEN`]
    /// bytes, or if `pair_secret` is empty — the shape a caller that forgot to
    /// open the seal, or that has no `TrustedPeer` record, would produce.
    /// Deriving from either would silently yield a PSK that is a pure function
    /// of the other half.
    pub fn derive(
        pair_secret: &[u8],
        epoch_seed: &[u8],
        twinnet_id: &str,
        epoch: u64,
    ) -> Result<Self> {
        if pair_secret.is_empty() {
            return Err(CryptoError::KeyLength {
                expected: 1,
                observed: 0,
            });
        }
        if epoch_seed.len() != EPOCH_SEED_LEN {
            return Err(CryptoError::KeyLength {
                expected: EPOCH_SEED_LEN,
                observed: epoch_seed.len(),
            });
        }

        // ikm = PairSecret(A,B) || EpochSeed(e)
        let mut ikm = Vec::with_capacity(pair_secret.len() + epoch_seed.len());
        ikm.extend_from_slice(pair_secret);
        ikm.extend_from_slice(epoch_seed);

        // salt = twinnet_id || e (u64 BE)
        let salt = psk_salt(twinnet_id, epoch);

        let mut derived = [0u8; PSK_LEN];
        let outcome = hkdf_sha256(Some(&salt), &ikm, PSK_INFO, &mut derived);
        // The intermediate `ikm` held the pairwise secret; erase it before any
        // early return can skip the erase.
        zeroize::Zeroize::zeroize(&mut ikm);
        outcome?;

        let bytes = LockedBytes::new_with(PSK_LEN, |dst| dst.copy_from_slice(&derived));
        zeroize::Zeroize::zeroize(&mut derived);
        Ok(Self {
            bytes: bytes?,
            epoch,
        })
    }

    /// The epoch this PSK belongs to.
    ///
    /// Not secret, and load-bearing: ADR-0007 §7.7 — "A device MUST NOT accept a
    /// handshake below its own `min_acceptable_epoch`."
    #[must_use]
    pub const fn epoch(&self) -> u64 {
        self.epoch
    }

    /// The 32 bytes, for the `psk2` slot.
    ///
    /// Named for its one destination. `snow`'s `Builder::psk` takes a
    /// `&[u8; 32]`, and this is what feeds it.
    #[must_use]
    pub fn as_psk_array(&self) -> [u8; PSK_LEN] {
        let mut out = [0u8; PSK_LEN];
        out.copy_from_slice(self.bytes.expose());
        out
    }
}

impl core::fmt::Debug for TwinNetPsk {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("TwinNetPsk")
            .field("epoch", &self.epoch)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const PAIR: [u8; 32] = [0x11; 32];
    const SEED: [u8; 32] = [0x22; 32];

    fn hex_of(bytes: &[u8; 32]) -> String {
        use core::fmt::Write as _;
        bytes.iter().fold(String::new(), |mut out, b| {
            let _ = write!(out, "{b:02x}");
            out
        })
    }

    fn derive(pair: &[u8], seed: &[u8], twinnet: &str, epoch: u64) -> [u8; 32] {
        TwinNetPsk::derive(pair, seed, twinnet, epoch)
            .expect("derive")
            .as_psk_array()
    }

    /// **The golden vector.** Computed from ADR-0007 §7.7 lines 654-657
    /// directly — `ikm = PairSecret || EpochSeed`, `salt = twinnet_id ||
    /// be64(epoch)`, `info = "TwinVPN/psk2/v1"` — and pinned here as a literal.
    ///
    /// A change to any parameter moves this value, and moving it is a
    /// **fleet-wide, irreversible** event: every paired device would have to
    /// re-derive, and a device on the old derivation cannot complete a handshake
    /// with one on the new. Editing this literal is therefore a deliberate,
    /// reviewable act, which is the whole reason it is a literal.
    #[test]
    fn the_derivation_matches_adr_0007_7_7_line_654() {
        let psk = derive(&PAIR, &SEED, "tn-example", 7);
        assert_eq!(
            hex_of(&psk),
            "8e086d9c4c2c8322a49607601d96bef989617567976b9d5c2dee5105d5eb0c59"
        );
    }

    /// The literal `info`, asserted against the ADR's text rather than against
    /// whatever the constant happens to hold.
    #[test]
    fn the_info_is_the_adrs_literal_with_nothing_appended() {
        assert_eq!(PSK_INFO, b"TwinVPN/psk2/v1");
        assert_eq!(PSK_INFO.len(), 15);
    }

    /// The salt is `twinnet_id || e (u64 BE)` — raw id bytes, then eight bytes
    /// of epoch, and nothing else.
    #[test]
    fn the_salt_is_the_twinnet_id_then_the_epoch_big_endian() {
        let salt = psk_salt("tn-example", 7);
        assert_eq!(&salt[..10], b"tn-example");
        assert_eq!(&salt[10..], &7u64.to_be_bytes());
        assert_eq!(salt.len(), 18);
        // The id goes in raw, not contracted: a 40-byte id yields a 48-byte
        // salt, which HKDF accepts because its salt is variable-length.
        assert_eq!(psk_salt(&"a".repeat(40), 1).len(), 48);
    }

    /// **Regression test for a real defect.** An earlier revision of this module
    /// read ADR-0001 §7.5's ellipsis as "unspecified" and used the RFC 5869 §2.2
    /// absent-salt case with a locally invented `info`. It is a fleet-wide
    /// incompatibility, so it gets a test that fails if it ever comes back.
    #[test]
    fn an_absent_salt_is_not_what_the_adr_specifies() {
        let correct = derive(&PAIR, &SEED, "tn-example", 7);

        // What the absent-salt reading would have produced, from the same ikm
        // and the same info.
        let mut wrong = [0u8; 32];
        let mut ikm = PAIR.to_vec();
        ikm.extend_from_slice(&SEED);
        crate::kdf::hkdf_sha256(None, &ikm, PSK_INFO, &mut wrong).expect("derive");

        assert_eq!(
            hex_of(&wrong),
            "85b1d68c70887d28ee4dd7aa85c10d21106a118cda6695dd53dd69c3a129fc4b"
        );
        assert_ne!(
            correct, wrong,
            "the salt must be twinnet_id || e, never absent"
        );
    }

    /// **The revocation lever, as an attack test.** A device that holds the
    /// `PairSecret` but was not sealed `EpochSeed(e+1)` must not be able to
    /// derive the next epoch's PSK — even though it knows the epoch advanced and
    /// knows the `twinnet_id`, both of which are public.
    #[test]
    fn a_revoked_device_holding_only_the_pair_secret_cannot_derive_the_next_epoch() {
        let current = derive(&PAIR, &SEED, "tn-1", 7);
        // The revoked device knows everything except EpochSeed(8), so the best
        // it can do is advance the epoch and reuse the seed it still has.
        let guessed = derive(&PAIR, &SEED, "tn-1", 8);
        let real = derive(&PAIR, &[0x33; 32], "tn-1", 8);
        assert_ne!(
            guessed, real,
            "advancing the epoch alone must not derive the new PSK"
        );
        assert_ne!(current, real);
    }

    /// **The reason the derivation is pairwise, as an attack test.** If the PSK
    /// were a function of a `TwinNet`-wide secret, every pair would share it and
    /// a revoked device would hold every other pair's key. Two different pairs
    /// at one epoch, with the same seed and the same `twinnet_id`, must differ —
    /// and the only thing that differs between them is `PairSecret`, which is
    /// exactly where ADR-0007 §7.7 puts the pairwise binding.
    #[test]
    fn two_different_pairs_at_one_epoch_derive_different_psks() {
        let first_pair = derive(&[0xa1; 32], &SEED, "tn-1", 3);
        let second_pair = derive(&[0xa2; 32], &SEED, "tn-1", 3);
        assert_ne!(first_pair, second_pair);
    }

    /// The peer identities are **not** inputs, and must not become inputs: they
    /// do not appear in ADR-0007 §7.7's formula. This test states the shape —
    /// `derive` takes four arguments and none of them is a `device_id` — so a
    /// future change that folded them in would have to delete it.
    #[test]
    fn the_peer_identities_are_not_inputs_to_the_derivation() {
        // Two devices deriving the same pair's PSK pass identical arguments;
        // there is no local/remote ordering to get wrong, and no argument a
        // caller could supply asymmetrically.
        let from_a = derive(&PAIR, &SEED, "tn-1", 4);
        let from_b = derive(&PAIR, &SEED, "tn-1", 4);
        assert_eq!(from_a, from_b);
    }

    /// The epoch is bound in through the salt.
    #[test]
    fn the_epoch_is_an_input_to_the_derivation() {
        let e7 = derive(&PAIR, &SEED, "tn-1", 7);
        let e8 = derive(&PAIR, &SEED, "tn-1", 8);
        assert_ne!(e7, e8);
        // And the epoch-8 value is the ADR's, not an accident of this code.
        assert_eq!(
            hex_of(&derive(&PAIR, &SEED, "tn-example", 8)),
            "6e182535352ce95f00bf268dd88d70cfc4ca8dc371262d3b1c624a7e3236a4e7"
        );
    }

    /// The `twinnet_id` is bound in through the salt, so a PSK derived in one
    /// `TwinNet` is useless in another.
    #[test]
    fn the_twinnet_id_is_an_input_to_the_derivation() {
        assert_ne!(
            derive(&PAIR, &SEED, "tn-1", 1),
            derive(&PAIR, &SEED, "tn-2", 1)
        );
    }

    /// **Attack test.** An `EpochSeed` of the wrong width would still derive a
    /// PSK, with less entropy than the revocation lever depends on and with
    /// nothing downstream noticing. ADR-0007 §7.7 fixes it at 32 bytes.
    #[test]
    fn an_epoch_seed_of_the_wrong_width_is_refused() {
        assert!(matches!(
            TwinNetPsk::derive(&PAIR, &[0u8; 16], "tn-1", 1),
            Err(CryptoError::KeyLength {
                expected: 32,
                observed: 16
            })
        ));
        assert!(TwinNetPsk::derive(&PAIR, &[0u8; 33], "tn-1", 1).is_err());
        assert!(TwinNetPsk::derive(&PAIR, &[], "tn-1", 1).is_err());
    }

    /// An empty `PairSecret` is refused rather than silently producing a PSK
    /// that is a function of the epoch seed alone.
    #[test]
    fn an_empty_pair_secret_is_refused() {
        assert!(TwinNetPsk::derive(b"", &SEED, "tn-1", 1).is_err());
    }

    #[test]
    fn debug_never_renders_the_secret() {
        let psk = TwinNetPsk::derive(&PAIR, &SEED, "tn-1", 5).expect("derive");
        let rendered = format!("{psk:?}");
        assert!(rendered.contains("epoch: 5"));
        assert!(!rendered.contains(&hex_of(&psk.as_psk_array())[..8]));
    }
}
