//! The lab seed file: one document, two halves, and the boundary that validates
//! it.
//!
//! `twinpeer seed` writes two of these — `guest.json`, copied into the disposable
//! guest and read by the service under its `lab-seed` feature, and `peer.json`,
//! which stays on the Hyper-V host and is read by `twinpeer serve`. They are the
//! **same shape with `local` and `peer` swapped**, because both ends build the
//! same [`TunnelKeying`] from the same facts and the only difference is which
//! side each is on.
//!
//! # This is a trust boundary
//!
//! The file arrives from outside the process. Every field is parsed and its
//! width checked here, once, and the rest of the crate works on
//! [`ResolvedSeed`], where a `[u8; 32]` is a `[u8; 32]` and an address is an
//! address. A malformed field is a named refusal, never a truncation and never a
//! default — the same rule `twinvpn_types`' identifiers apply one layer down.
//!
//! # Never a release artifact
//!
//! The material here is generated by a lab tool and the peer's static key sits
//! in a JSON file. That is acceptable **only** because nothing that reads it
//! ships: `lab-peer` and `lab-seed` are both absent from every default and every
//! `full` feature set.

use anyhow::{bail, Context as _, Result};
use serde::{Deserialize, Serialize};
use twinvpn_core::lab::TunnelKeying;
use twinvpn_crypto::locked::LockedBytes;
use twinvpn_crypto::prologue::NegotiationBinding;
use twinvpn_crypto::psk::TwinNetPsk;
use twinvpn_types::{DeviceId, Endpoint, IpAddr, Port, TwinnetId, V4Addr, V6Addr};

/// One half of the seed, as it appears on disk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeedFile {
    /// The `TwinNet` both ends name in the PSK salt and the identity binding.
    pub twinnet_id: String,
    /// This half's own device.
    pub local: LocalHalf,
    /// The other end.
    pub peer: PeerHalf,
    /// What `TwinNetPSK(A, B, epoch)` is derived from (ADR-0007 §7.7).
    pub psk: PskMaterial,
    /// ADR-0014 N-6's negotiation binding.
    pub negotiation: NegotiationMaterial,
    /// The pinned anchor version both ends cover in the prologue.
    pub anchor_version: u32,
    /// The pinned delegation-set digest, hex, 32 bytes.
    pub delegation_set_digest: String,
    /// ADR-0007 N-20's epoch, which the prologue covers.
    ///
    /// `0` for a seeded view: nothing has written a trust epoch into the store.
    pub trust_epoch: u64,
}

/// This end's own identity and overlay addresses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalHalf {
    /// Hex, 32 bytes.
    pub device_id: String,
    /// The L-DATA X25519 static private key, hex, 32 bytes.
    pub static_private: String,
    /// This end's overlay IPv4 address.
    pub overlay_v4: String,
    /// This end's overlay IPv6 address.
    pub overlay_v6: String,
    /// Where this end listens. **`peer.json` only** — the guest's socket is the
    /// core's and its port is ephemeral.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bind: Option<String>,
}

/// The other end's identity and overlay addresses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PeerHalf {
    /// Hex, 32 bytes.
    pub device_id: String,
    /// The peer's L-DATA X25519 static **public** key, hex, 32 bytes.
    pub static_public: String,
    /// The peer's overlay IPv4 address.
    pub overlay_v4: String,
    /// The peer's overlay IPv6 address.
    pub overlay_v6: String,
    /// Where to send the initiation. **`guest.json` only**: the peer learns the
    /// guest's endpoint from the initiation's source address, which is the only
    /// value that can be right through a NAT.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
}

/// The PSK's inputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PskMaterial {
    /// The pairwise `PairSecret`, hex, 32 bytes.
    pub pair_secret: String,
    /// The plaintext `EpochSeed(epoch)`, hex, 32 bytes.
    pub epoch_seed: String,
    /// Which epoch.
    pub epoch: u64,
}

/// The negotiation binding's inputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NegotiationMaterial {
    /// `H_initiator`, hex, 32 bytes.
    pub h_initiator: String,
    /// `H_responder`, hex, 32 bytes.
    pub h_responder: String,
    /// `det_CBOR(Selection)`, hex, any length.
    pub selection_dcbor: String,
}

/// The same document, parsed. Nothing downstream re-validates.
#[derive(Debug, Clone)]
pub struct ResolvedSeed {
    /// The `TwinNet`.
    pub twinnet: TwinnetId,
    /// The `TwinNet`'s text form, which the PSK derivation salts with.
    pub twinnet_text: String,
    /// This end's device.
    pub local_device: DeviceId,
    /// This end's static private key.
    pub local_static: [u8; 32],
    /// This end's overlay addresses.
    pub local_overlay: (IpAddr, IpAddr),
    /// Where this end listens, on the half that carries it.
    pub bind: Option<Endpoint>,
    /// The other end's device.
    pub peer_device: DeviceId,
    /// The other end's static public key.
    pub peer_static: [u8; 32],
    /// The other end's overlay addresses.
    pub peer_overlay: (IpAddr, IpAddr),
    /// Where to reach the other end, on the half that carries it.
    pub peer_endpoint: Option<Endpoint>,
    /// The PSK inputs.
    pub pair_secret: [u8; 32],
    /// The epoch seed.
    pub epoch_seed: [u8; 32],
    /// The PSK epoch.
    pub psk_epoch: u64,
    /// The negotiation binding.
    pub negotiation: NegotiationBinding,
    /// The pinned anchor version.
    pub anchor_version: u32,
    /// The pinned delegation-set digest.
    pub delegation_set_digest: [u8; 32],
    /// The trust epoch the prologue covers.
    pub trust_epoch: u64,
}

impl SeedFile {
    /// Parses and validates every field.
    ///
    /// # Errors
    ///
    /// The first malformed field, named. A width mismatch is rejected rather
    /// than truncated or padded.
    pub fn resolve(&self) -> Result<ResolvedSeed> {
        Ok(ResolvedSeed {
            twinnet: TwinnetId::new(&self.twinnet_id)
                .map_err(|e| anyhow::anyhow!("twinnet_id: {e}"))?,
            twinnet_text: self.twinnet_id.clone(),
            local_device: device("local.device_id", &self.local.device_id)?,
            local_static: hex32("local.static_private", &self.local.static_private)?,
            local_overlay: (
                address("local.overlay_v4", &self.local.overlay_v4)?,
                address("local.overlay_v6", &self.local.overlay_v6)?,
            ),
            bind: self
                .local
                .bind
                .as_deref()
                .map(|text| endpoint("local.bind", text))
                .transpose()?,
            peer_device: device("peer.device_id", &self.peer.device_id)?,
            peer_static: hex32("peer.static_public", &self.peer.static_public)?,
            peer_overlay: (
                address("peer.overlay_v4", &self.peer.overlay_v4)?,
                address("peer.overlay_v6", &self.peer.overlay_v6)?,
            ),
            peer_endpoint: self
                .peer
                .endpoint
                .as_deref()
                .map(|text| endpoint("peer.endpoint", text))
                .transpose()?,
            pair_secret: hex32("psk.pair_secret", &self.psk.pair_secret)?,
            epoch_seed: hex32("psk.epoch_seed", &self.psk.epoch_seed)?,
            psk_epoch: self.psk.epoch,
            negotiation: NegotiationBinding {
                h_initiator: hex32("negotiation.h_initiator", &self.negotiation.h_initiator)?,
                h_responder: hex32("negotiation.h_responder", &self.negotiation.h_responder)?,
                selection_dcbor: unhex(
                    "negotiation.selection_dcbor",
                    &self.negotiation.selection_dcbor,
                )?,
            },
            anchor_version: self.anchor_version,
            delegation_set_digest: hex32("delegation_set_digest", &self.delegation_set_digest)?,
            trust_epoch: self.trust_epoch,
        })
    }
}

impl ResolvedSeed {
    /// Assembles the key material for one `Noise_IKpsk2` handshake.
    ///
    /// Both ends run this on their own half, and the two must agree byte for
    /// byte: `TunnelKeying::prologue` takes the initiator and responder as
    /// **roles** rather than as "us and them", so the only thing that has to
    /// match here is the material itself.
    ///
    /// # Errors
    ///
    /// A locked allocation that could not be made, or a PSK derivation the
    /// crypto crate refused.
    pub fn keying(&self) -> Result<TunnelKeying> {
        let local_static = LockedBytes::new_with(self.local_static.len(), |slot| {
            slot.copy_from_slice(&self.local_static);
        })
        .context("the L-DATA static could not be placed in the locked allocator")?;
        // The ONLY way to build a `VerifiedTunnelKey`: the fixture signs a
        // `TunnelKeyBinding`, verifies the COSE_Sign1 over its octets and then
        // verifies the binding. ADR-0007 N-4's gate is exercised, not skipped.
        let peer_key = twinvpn_crypto::testkit::verified_tunnel_key(&self.peer_static);
        let psk = TwinNetPsk::derive(
            &self.pair_secret,
            &self.epoch_seed,
            &self.twinnet_text,
            self.psk_epoch,
        )
        .map_err(|e| anyhow::anyhow!("the TwinNetPSK could not be derived: {e}"))?;
        TunnelKeying::new(
            local_static,
            peer_key,
            psk,
            self.negotiation.clone(),
            self.local_device,
            self.twinnet.clone(),
            self.anchor_version,
            self.delegation_set_digest,
        )
        .context("the L-DATA static is not 32 bytes")
    }
}

/// Lower-case hex, for the fields this tool writes.
#[must_use]
pub fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(char::from_digit(u32::from(b >> 4), 16).unwrap_or('0'));
        out.push(char::from_digit(u32::from(b & 0x0f), 16).unwrap_or('0'));
    }
    out
}

fn unhex(field: &str, text: &str) -> Result<Vec<u8>> {
    if !text.len().is_multiple_of(2) {
        bail!("{field}: an odd number of hex digits");
    }
    let bytes = text.as_bytes();
    let mut out = Vec::with_capacity(text.len() / 2);
    for pair in bytes.chunks_exact(2) {
        let hi = (pair[0] as char)
            .to_digit(16)
            .with_context(|| format!("{field}: `{}` is not a hex digit", pair[0] as char))?;
        let lo = (pair[1] as char)
            .to_digit(16)
            .with_context(|| format!("{field}: `{}` is not a hex digit", pair[1] as char))?;
        #[allow(clippy::cast_possible_truncation)]
        out.push(((hi << 4) | lo) as u8);
    }
    Ok(out)
}

fn hex32(field: &str, text: &str) -> Result<[u8; 32]> {
    let bytes = unhex(field, text)?;
    let mut out = [0u8; 32];
    if bytes.len() != out.len() {
        bail!("{field}: {} bytes, expected 32", bytes.len());
    }
    out.copy_from_slice(&bytes);
    Ok(out)
}

fn device(field: &str, text: &str) -> Result<DeviceId> {
    Ok(DeviceId::from_array(hex32(field, text)?))
}

/// One address, in either family, as `twinvpn_types` spells it.
///
/// `std::net` parses and this converts, rather than a parser written here: the
/// zone and v4-mapped rules `V6Addr::new` enforces are the product's and are
/// not restated.
fn address(field: &str, text: &str) -> Result<IpAddr> {
    match text
        .parse::<std::net::IpAddr>()
        .with_context(|| format!("{field}: `{text}` is not an IP address"))?
    {
        std::net::IpAddr::V4(a) => Ok(IpAddr::V4(V4Addr::from_octets(a.octets()))),
        std::net::IpAddr::V6(a) => Ok(IpAddr::V6(
            V6Addr::new(a.octets(), None).map_err(|e| anyhow::anyhow!("{field}: {e}"))?,
        )),
    }
}

fn endpoint(field: &str, text: &str) -> Result<Endpoint> {
    let socket: std::net::SocketAddr = text
        .parse()
        .with_context(|| format!("{field}: `{text}` is not an address:port"))?;
    let port = Port::new(socket.port()).map_err(|e| anyhow::anyhow!("{field}: {e}"))?;
    Ok(Endpoint::new(
        address(field, &socket.ip().to_string())?,
        port,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use twinvpn_types::Identifier as _;

    /// A well-formed peer half, in the exact shape `twinpeer seed` writes.
    fn peer_json() -> String {
        let guest_static = [7u8; 32];
        let guest_public = twinvpn_crypto::noise::static_public_key(
            &LockedBytes::new_with(32, |s| s.copy_from_slice(&guest_static)).expect("locked"),
        )
        .expect("public half");
        format!(
            r#"{{
  "twinnet_id": "tn-lab",
  "local": {{
    "device_id": "{}",
    "static_private": "{}",
    "overlay_v4": "100.64.1.2",
    "overlay_v6": "fd7c:9e5d:2a10:1::2",
    "bind": "10.77.0.1:51820"
  }},
  "peer": {{
    "device_id": "{}",
    "static_public": "{}",
    "overlay_v4": "100.64.1.1",
    "overlay_v6": "fd7c:9e5d:2a10:1::1"
  }},
  "psk": {{ "pair_secret": "{}", "epoch_seed": "{}", "epoch": 1 }},
  "negotiation": {{ "h_initiator": "{}", "h_responder": "{}", "selection_dcbor": "{}" }},
  "anchor_version": 1,
  "delegation_set_digest": "{}",
  "trust_epoch": 0
}}"#,
            hex(&[0xbb; 32]),
            hex(&[0x11; 32]),
            hex(&[0xaa; 32]),
            hex(&guest_public),
            hex(&[0x21; 32]),
            hex(&[0x22; 32]),
            hex(&[0x31; 32]),
            hex(&[0x32; 32]),
            hex(b"twinpeer-lab-selection-v1"),
            hex(&[0x41; 32]),
        )
    }

    #[test]
    fn a_well_formed_peer_half_resolves_and_yields_keying() {
        let file: SeedFile = serde_json::from_str(&peer_json()).expect("parses");
        let resolved = file.resolve().expect("resolves");
        assert_eq!(resolved.local_device.to_hex(), hex(&[0xbb; 32]));
        assert_eq!(
            resolved.bind.expect("peer.json carries a bind").port.get(),
            51820
        );
        assert!(
            resolved.peer_endpoint.is_none(),
            "the peer learns the guest's endpoint from the initiation's source"
        );
        assert_eq!(
            resolved.negotiation.selection_dcbor,
            b"twinpeer-lab-selection-v1"
        );
        // The real gate: `TunnelKeying::new` takes a `VerifiedTunnelKey`, so a
        // seed that produces one has been through `verify_tunnel_key_binding`.
        let keying = resolved.keying().expect("keying");
        assert_eq!(keying.twinnet().as_str(), "tn-lab");
    }

    #[test]
    fn a_short_key_is_refused_by_name_rather_than_padded() {
        let text = peer_json().replace(&hex(&[0x11; 32]), &hex(&[0x11; 31]));
        let file: SeedFile = serde_json::from_str(&text).expect("parses");
        let error = file.resolve().expect_err("refuses").to_string();
        assert!(
            error.contains("local.static_private") && error.contains("31 bytes"),
            "the refusal must name the field and the width: {error}"
        );
    }

    #[test]
    fn a_non_hex_digit_is_refused_by_name() {
        let text = peer_json().replace(&hex(&[0x41; 32]), &"z".repeat(64));
        let file: SeedFile = serde_json::from_str(&text).expect("parses");
        let error = file.resolve().expect_err("refuses").to_string();
        assert!(
            error.contains("delegation_set_digest"),
            "the refusal must name the field: {error}"
        );
    }

    #[test]
    fn a_zero_port_is_refused_rather_than_bound() {
        let text = peer_json().replace("10.77.0.1:51820", "10.77.0.1:0");
        let file: SeedFile = serde_json::from_str(&text).expect("parses");
        let error = file.resolve().expect_err("refuses").to_string();
        assert!(error.contains("local.bind"), "{error}");
    }

    #[test]
    fn both_halves_derive_the_same_psk_from_the_same_material() {
        // The property the whole seed rests on: two files with `local` and
        // `peer` swapped must produce one PSK, because `TwinNetPSK` is pairwise
        // and salted only by the twinnet id and the epoch.
        let file: SeedFile = serde_json::from_str(&peer_json()).expect("parses");
        let peer = file.resolve().expect("resolves");
        let mut swapped = file.clone();
        std::mem::swap(&mut swapped.local.device_id, &mut swapped.peer.device_id);
        swapped.local.bind = None;
        swapped.peer.endpoint = Some("10.77.0.1:51820".to_owned());
        let guest = swapped.resolve().expect("resolves");

        let a = TwinNetPsk::derive(
            &peer.pair_secret,
            &peer.epoch_seed,
            &peer.twinnet_text,
            peer.psk_epoch,
        )
        .expect("derives");
        let b = TwinNetPsk::derive(
            &guest.pair_secret,
            &guest.epoch_seed,
            &guest.twinnet_text,
            guest.psk_epoch,
        )
        .expect("derives");
        assert_eq!(a.epoch(), b.epoch());
        assert_eq!(peer.negotiation.hash(), guest.negotiation.hash());
    }
}
