//! Compiles `contracts/registry/reason_codes.json` into a static Rust table.
//!
//! **Why a build script rather than a runtime parse.** ADR-0015 §11.2 makes the
//! registry the sole authority for every `reason_code` and its attributes, and
//! `docs/implementation/ownership.md` §6 rule 12 requires every exposed error to
//! be a registered code. Turning the frozen registry into a `static` array at
//! build time makes that structural: a code that is not in the registry has no
//! constant to name, `ReasonCode` has no public constructor from an arbitrary
//! string, and the table cannot drift from `contracts/` because
//! `cargo:rerun-if-changed` re-runs this script whenever the registry moves.
//!
//! `serde_json` is a **build-dependency only**. The compiled crate links
//! `thiserror` and nothing else, so `twinvpn-types` stays the zero-dependency
//! vocabulary crate ADR-0018 §11.7 places at the root of the arrows.
//!
//! The registry itself is FROZEN (`contracts/FROZEN`). This script only reads it.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// The frozen registry, relative to this crate's manifest directory.
const REGISTRY_REL: &str = "../../../contracts/registry/reason_codes.json";

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let registry = manifest.join(REGISTRY_REL);
    println!("cargo:rerun-if-changed={}", registry.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = std::fs::read_to_string(&registry)
        .unwrap_or_else(|e| panic!("cannot read frozen registry {}: {e}", registry.display()));
    let doc: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("registry is not valid JSON: {e}"));

    let generated = generate(&doc);
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("reason_registry.rs");
    std::fs::write(&out, generated).expect("write generated registry");
}

fn generate(doc: &serde_json::Value) -> String {
    let registry_version = doc["registry_version"]
        .as_u64()
        .expect("registry_version is a number");

    let domains: Vec<String> = doc["closed_domain_set"]
        .as_array()
        .expect("closed_domain_set is an array")
        .iter()
        .map(|v| v.as_str().expect("domain is a string").to_owned())
        .collect();
    assert_eq!(
        domains.len(),
        16,
        "ADR-0015 §11.2 fixes a CLOSED SET OF SIXTEEN domains; the registry now declares {}. \
         Admitting a seventeenth is an ADR-0015 amendment, not a build-script change.",
        domains.len()
    );

    // Sorted, so the emitted table can be binary-searched and so the generated
    // file is byte-stable across runs.
    let mut entries: BTreeMap<String, &serde_json::Value> = BTreeMap::new();
    for e in doc["reason_codes"]
        .as_array()
        .expect("reason_codes is an array")
    {
        let code = e["reason_code"].as_str().expect("reason_code is a string");
        assert!(
            entries.insert(code.to_owned(), e).is_none(),
            "duplicate reason_code {code} in the frozen registry"
        );
    }

    let mut out = String::with_capacity(256 * 1024);
    out.push_str(
        "// @generated by twinvpn-types/build.rs from contracts/registry/reason_codes.json.\n",
    );
    out.push_str(
        "// DO NOT EDIT. The registry is frozen; edit neither this file nor the registry.\n\n",
    );

    writeln!(
        out,
        "/// Append-only version of the frozen reason-code registry this build embeds\n\
         /// (ADR-0015 §11.2 rule 6). Carried in `SchemaDescriptor.reason_registry_version`.\n\
         pub const REASON_REGISTRY_VERSION: u32 = {registry_version};\n"
    )
    .unwrap();

    emit_domain_enum(&mut out, &domains);
    emit_entries(&mut out, &entries, &domains);
    emit_constants(&mut out, &entries);
    out
}

fn emit_domain_enum(out: &mut String, domains: &[String]) {
    out.push_str(
        "/// The closed set of sixteen `reason_code` domains (ADR-0015 §11.2).\n\
         ///\n\
         /// `DOMAIN` is the **only** segment with registry meaning: forward\n\
         /// compatibility is by domain prefix, so a receiver meeting an unknown code\n\
         /// degrades on this value. The set is closed by an admission rule — a new\n\
         /// top-level domain is admissible only when no existing domain is a correct\n\
         /// owner — so a first segment outside this set is not a code this build can\n\
         /// degrade correctly, and is rejected rather than guessed at.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         #[non_exhaustive]\n\
         pub enum Domain {\n",
    );
    for d in domains {
        writeln!(out, "    /// The `{d}` domain.\n    {},", camel(d)).unwrap();
    }
    out.push_str("}\n\n");

    out.push_str("impl Domain {\n");
    out.push_str("    /// Every domain in the closed set, in registry order.\n");
    writeln!(out, "    pub const ALL: [Domain; {}] = [", domains.len()).unwrap();
    for d in domains {
        writeln!(out, "        Domain::{},", camel(d)).unwrap();
    }
    out.push_str("    ];\n\n");
    out.push_str("    /// The domain's wire spelling — the first segment of a `reason_code`.\n");
    out.push_str(
        "    #[must_use]\n    pub const fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for d in domains {
        writeln!(out, "            Domain::{} => \"{d}\",", camel(d)).unwrap();
    }
    out.push_str("        }\n    }\n\n");
    out.push_str(
        "    /// Parses a first segment against the closed set.\n\
         ///\n\
         /// Returns `None` for anything outside it, including lower-case spellings:\n\
         /// the taxonomy is uppercase ASCII and a case-insensitive match would let one\n\
         /// domain arrive under two encodings.\n\
         #[must_use]\n    pub fn parse(s: &str) -> Option<Domain> {\n        match s {\n",
    );
    for d in domains {
        writeln!(out, "            \"{d}\" => Some(Domain::{}),", camel(d)).unwrap();
    }
    out.push_str("            _ => None,\n        }\n    }\n}\n\n");
}

fn emit_entries(
    out: &mut String,
    entries: &BTreeMap<String, &serde_json::Value>,
    domains: &[String],
) {
    writeln!(
        out,
        "pub(crate) static ENTRIES: [ReasonCodeEntry; {}] = [",
        entries.len()
    )
    .unwrap();

    for (code, e) in entries {
        let domain = e["domain"].as_str().expect("domain");
        assert!(
            domains.iter().any(|d| d == domain),
            "{code} declares domain {domain}, which is outside the closed set"
        );
        assert!(
            code.starts_with(&format!("{domain}.")),
            "{code} does not begin with its declared domain {domain}"
        );
        let segments = code.split('.').count();
        assert!(
            (2..=3).contains(&segments),
            "ADR-0015 §11.2 rule 7: {code} has {segments} segments; two or three are permitted"
        );
        assert!(
            code.len() <= 64,
            "{code} is {} bytes; the cap is 64",
            code.len()
        );
        assert!(
            code.bytes()
                .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_' || b == b'.'),
            "{code} is not uppercase ASCII with `_` and `.` separators"
        );

        let user_actionable = e["user_actionable"].as_bool().expect("user_actionable");
        let next_action = e.get("next_action_key").and_then(|v| v.as_str());
        assert!(
            !user_actionable || next_action.is_some(),
            "ADR-0015 §11.2: {code} is user_actionable with no next_action_key"
        );

        let evidence: Vec<&str> = e
            .get("evidence_fields")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .map(|v| v.as_str().expect("evidence field is a string"))
                    .collect()
            })
            .unwrap_or_default();
        for key in &evidence {
            assert!(
                key.len() <= 48,
                "{code} declares evidence key {key} of {} bytes; the cap is 48",
                key.len()
            );
            assert!(
                !key.is_empty()
                    && key.as_bytes()[0].is_ascii_lowercase()
                    && key
                        .bytes()
                        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'),
                "{code} declares evidence key {key}, which is not lower_snake_case"
            );
        }

        writeln!(out, "    ReasonCodeEntry {{").unwrap();
        writeln!(out, "        code: {},", quote(code)).unwrap();
        writeln!(out, "        domain: Domain::{},", camel(domain)).unwrap();
        writeln!(
            out,
            "        class: ErrorClass::{},",
            camel(e["class"].as_str().expect("class"))
        )
        .unwrap();
        writeln!(
            out,
            "        severity: ErrorSeverity::{},",
            camel(e["severity"].as_str().expect("severity"))
        )
        .unwrap();
        writeln!(
            out,
            "        terminal: {},",
            e["terminal"].as_bool().expect("terminal")
        )
        .unwrap();
        writeln!(out, "        user_actionable: {user_actionable},").unwrap();
        writeln!(
            out,
            "        remediation_class: RemediationClass::{},",
            camel(e["remediation_class"].as_str().expect("remediation_class"))
        )
        .unwrap();
        writeln!(
            out,
            "        scope: DiagnosticScope::{},",
            camel(e["scope"].as_str().expect("scope"))
        )
        .unwrap();
        writeln!(
            out,
            "        doc_anchor: {},",
            quote(e["doc_anchor"].as_str().expect("doc_anchor"))
        )
        .unwrap();
        writeln!(
            out,
            "        summary_key: {},",
            quote(e["summary_key"].as_str().expect("summary_key"))
        )
        .unwrap();
        match next_action {
            Some(k) => writeln!(out, "        next_action_key: Some({}),", quote(k)).unwrap(),
            None => out.push_str("        next_action_key: None,\n"),
        }
        writeln!(
            out,
            "        status: CodeStatus::{},",
            camel(e["status"].as_str().expect("status"))
        )
        .unwrap();
        out.push_str("        evidence_fields: &[");
        for key in &evidence {
            write!(out, "{}, ", quote(key)).unwrap();
        }
        out.push_str("],\n    },\n");
    }
    out.push_str("];\n\n");
}

fn emit_constants(out: &mut String, entries: &BTreeMap<String, &serde_json::Value>) {
    out.push_str(
        "/// A `ReasonCode` constant for every code in the frozen registry.\n\
         ///\n\
         /// Naming: the code with `.` replaced by `_`. These are the only way to name a\n\
         /// code at a call site, which is what makes \"expose registered reason codes,\n\
         /// never raw internal errors\" a compile-time property rather than a review one.\n\
         pub mod codes {\n    use super::{ReasonCode, ENTRIES};\n\n",
    );
    for (index, (code, e)) in entries.iter().enumerate() {
        let condition = e
            .get("condition")
            .and_then(|v| v.as_str())
            .unwrap_or("(no condition recorded)");
        writeln!(
            out,
            "    /// `{code}` — {}\n    pub const {}: ReasonCode = ReasonCode(&ENTRIES[{index}]);",
            doc_escape(condition),
            code.replace('.', "_")
        )
        .unwrap();
    }
    out.push_str("}\n");
}

/// `SCREAMING_SNAKE` (or `DOTTED.SCREAMING_SNAKE`) to `UpperCamel`.
fn camel(s: &str) -> String {
    s.split(['_', '.'])
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + &c.as_str().to_ascii_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Registry `condition` text goes into a doc comment; it must not break out of one.
fn doc_escape(s: &str) -> String {
    s.replace(['\n', '\r'], " ").replace("*/", "* /")
}
